parser: babel-eslint

extends:
  - airbnb
  - plugin:prettier/recommended
  - prettier/react

env:
  browser: true
  node: true
  jest: true
  es6: true

plugins:
  - redux-saga
  - react
  - jsx-a11y

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  import/resolver:
    webpack:
      config: './internals/webpack/webpack.prod.babel.js'

overrides:
  - files:
      - '*.test.js'
    rules:
      max-nested-callbacks: 'off'
      max-statements: 'off'

rules:
  prettier/prettier:
    - error
    - trailingComma: all
      singleQuote: true

  max-lines:
    - warn
    - 300
  max-depth:
    - warn
    - 2
  max-params:
    - error
    - 3
  max-nested-callbacks:
    - error
    - 3
  complexity:
    - off
    - 6
  no-else-return: 2
  no-lonely-if: 2
  no-plusplus: 0
  no-nested-ternary: 0
  no-continue: 0
  no-restricted-syntax: 0
  no-confusing-arrow: 0
  no-console: 1
  no-restricted-imports:
    - error
    - patterns:
        - '**/../core/**'
  no-duplicate-imports: 2
  no-unused-vars: 2
  no-use-before-define: 0
  object-shorthand: 2
  function-paren-newline: 0
  class-methods-use-this: 0
  newline-per-chained-call: 0
  prefer-template: 2
  prefer-destructuring: 2
  prefer-spread: 2
  prefer-arrow-callback: 2

  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - const
        - let
        - var
        - import
      next: '*'
    - blankLine: any
      prev:
        - const
        - let
        - var
        - import
      next:
        - const
        - let
        - var
        - import
    - blankLine: always
      prev: directive
      next: '*'
    - blankLine: any
      prev: directive
      next: directive
    - blankLine: always
      prev: '*'
      next: return

  import/no-named-as-default: 0
  import/no-dynamic-require: 0
  import/no-extraneous-dependencies: 0
  import/imports-first: 2
  import/first: 2
  import/newline-after-import: 2
  import/namespace: 2
  import/no-absolute-path: 2
  import/no-duplicates: 2
  import/no-unresolved: 2
  import/no-useless-path-segments: 2
  import/no-self-import: 2
  import/no-cycle: 2
  import/no-named-as-default-member: 2
  import/no-mutable-exports: 2
  import/export: 2
  import/named: 2
  import/default: 2
  import/no-internal-modules: 0
  import/no-namespace: 2
  import/no-webpack-loader-syntax: 0
  import/prefer-default-export: 0

  jsx-a11y/aria-props: 2
  jsx-a11y/heading-has-content: 0
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - to
  jsx-a11y/label-has-for: 2
  jsx-a11y/no-href: 0
  jsx-a11y/mouse-events-have-key-events: 2
  jsx-a11y/role-has-required-aria-props: 2
  jsx-a11y/role-supports-aria-props: 2

  react/jsx-filename-extension: 0
  react/jsx-no-target-blank: 0

  react/prefer-stateless-function: 2
  react/forbid-prop-types: 0
  react/require-default-props: 0
  react/require-extension: 0
  react/self-closing-comp: 0
  react/no-unused-prop-types: 2
  redux-saga/no-yield-in-race: 2
  redux-saga/yield-effects: 2
  require-yield: 0
